"use client";

import { useState } from "react";
import { Building2, FileSignature, Search, UserRound, Zap } from "lucide-react";
import { GamePanel, LivePill } from "@/components/game-ui";
import { Button } from "@/components/ui";

const messages = [
  {from:"Arsenal FC",title:"Revised offer: Enzo Martínez",preview:"We are prepared to improve the structure and include a sell-on clause.",time:"8m",type:"CLUB",urgent:true,icon:Building2},
  {from:"Marcus Rashford",title:"Career direction meeting",preview:"Can we schedule time to discuss the Milan interest before training?",time:"32m",type:"PLAYER",urgent:true,icon:UserRound},
  {from:"Global Market AI",title:"Market alert: Left wingers",preview:"Demand increased 18% across the Premier League and Serie A.",time:"1h",type:"ALERT",urgent:false,icon:Zap},
  {from:"Brighton & Hove Albion",title:"Contract renewal package",preview:"Please find our formal proposal for Noah Williams attached.",time:"3h",type:"CONTRACT",urgent:false,icon:FileSignature},
  {from:"South America Desk",title:"Scout report: Mateo Silva",preview:"Final assessment complete. Recommendation: immediate approach.",time:"5h",type:"SCOUT",urgent:false,icon:Search},
];

export default function Inbox() {
  const [selected,setSelected]=useState(0);
  const message=messages[selected];
  const Icon=message.icon;
  return <div className="mx-auto max-w-[1500px] animate-in"><div className="mb-6"><div className="mb-2 flex items-center gap-3"><LivePill>5 unread</LivePill><span className="text-[8px] font-bold uppercase tracking-wider text-slate-700">Career communications</span></div><h1 className="font-display text-3xl uppercase italic sm:text-[42px]">Inbox</h1><p className="mt-1.5 text-xs text-slate-500">Every opportunity, request and decision in one live feed.</p></div>
    <GamePanel className="grid min-h-[650px] overflow-hidden lg:grid-cols-[360px_1fr]"><aside className="border-b border-white/[.07] bg-black/[.08] lg:border-b-0 lg:border-r"><div className="border-b border-white/[.07] p-4"><div className="relative"><Search size={13} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-600"/><input placeholder="Search messages..." className="h-9 w-full rounded-lg border border-white/[.07] bg-black/20 pl-9 text-[9px] outline-none transition placeholder:text-slate-700 focus:border-cyan-300/25"/></div><div className="mt-3 flex gap-1">{["ALL","URGENT","CLUBS","PLAYERS"].map((x,i)=><button key={x} data-active={i===0} className={`tab-button rounded-md px-2.5 py-1.5 text-[7px] font-black tracking-wider ${i===0?"bg-cyan-300/10 text-cyan-300":"text-slate-600"}`}>{x}</button>)}</div></div><div className="max-h-[540px] overflow-y-auto">{messages.map((m,i)=>{const I=m.icon;return <button key={m.title} onClick={()=>setSelected(i)} className={`live-row flex w-full gap-3 border-b border-white/[.05] p-4 text-left ${selected===i?"bg-gradient-to-r from-cyan-300/[.09] to-transparent":"hover:bg-white/[.02]"}`} style={{"--row-accent":m.urgent?"#fb7185":"#22d3ee"} as React.CSSProperties}><span className={`interactive-icon grid size-9 shrink-0 place-items-center rounded-lg border ${m.urgent?"border-rose-300/20 bg-rose-300/[.07] text-rose-300":"border-white/[.07] bg-white/[.03] text-slate-500"}`}><I size={14}/></span><div className="min-w-0 flex-1"><div className="flex justify-between"><p className="truncate text-[9px] font-black uppercase">{m.from}</p><span className="text-[7px] text-slate-700">{m.time}</span></div><p className="mt-1 truncate text-[9px] font-bold text-slate-300">{m.title}</p><p className="mt-1 truncate text-[8px] text-slate-600">{m.preview}</p></div>{m.urgent&&<span className="pulse-live mt-1 size-1.5 rounded-full bg-rose-400"/>}</button>})}</div></aside>
      <article key={message.title} className="animate-in p-5 sm:p-8"><div className="flex flex-col justify-between gap-4 border-b border-white/[.07] pb-6 sm:flex-row"><div className="flex gap-4"><span className="premium-ring grid size-11 shrink-0 place-items-center rounded-xl border border-cyan-300/15 bg-cyan-300/[.06] text-cyan-300"><Icon size={18}/></span><div><div className="flex items-center gap-2"><p className="text-[9px] font-black uppercase tracking-wider text-cyan-300">{message.from}</p>{message.urgent&&<span className="rounded bg-rose-400/10 px-2 py-1 text-[7px] font-black text-rose-300">URGENT</span>}</div><h2 className="mt-2 text-lg font-black uppercase italic">{message.title}</h2><p className="mt-1 text-[8px] text-slate-600">Received today · Secure channel</p></div></div><button className="interactive-icon text-[8px] font-black uppercase text-slate-600">•••</button></div><div className="max-w-2xl py-8 text-[11px] leading-7 text-slate-400"><p>Alex,</p><p className="mt-4">{message.preview}</p><p className="mt-4">Our sporting director has authorized an improved package of <strong className="text-white">€42.5 million</strong>, with performance bonuses and a future sell-on percentage. We believe this reflects the player&apos;s trajectory and our serious intent.</p><div className="premium-ring my-6 rounded-xl border border-cyan-300/10 bg-cyan-300/[.035] p-5"><p className="text-[8px] font-black uppercase tracking-[.15em] text-cyan-300">Offer Intelligence</p><div className="mt-4 grid grid-cols-3"><div><p className="text-[8px] text-slate-600">BASE</p><p className="number-glow mt-1 text-sm font-black">€42.5M</p></div><div className="border-l border-white/[.07] pl-4"><p className="text-[8px] text-slate-600">BONUSES</p><p className="mt-1 text-sm font-black">€4.0M</p></div><div className="border-l border-white/[.07] pl-4"><p className="text-[8px] text-slate-600">SELL-ON</p><p className="mt-1 text-sm font-black">12%</p></div></div></div><p>We would appreciate a response before tomorrow&apos;s board meeting.</p><p className="mt-5 text-slate-300">James Whitaker<br/><span className="text-slate-600">Sporting Director</span></p></div><div className="flex gap-2 border-t border-white/[.07] pt-5"><Button>Enter Negotiation</Button><Button variant="secondary">Reply</Button></div></article>
    </GamePanel>
  </div>;
}
