import Image from "next/image";
import { BrainCircuit, Crosshair, Globe2, Radar, Sparkles, Star, Telescope } from "lucide-react";
import { GamePanel, LivePill, SectionHeader, StatTile } from "@/components/game-ui";
import { Button } from "@/components/ui";

const prospects = [
  {name:"Mateo Silva",age:17,pos:"CAM",region:"Brazil",ovr:67,pot:94,stars:5,img:"https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&q=85", tag:"HIDDEN GEM"},
  {name:"Ibrahim Diallo",age:18,pos:"ST",region:"France",ovr:71,pot:91,stars:5,img:"https://images.unsplash.com/photo-1531384441138-2736e62e0919?auto=format&fit=crop&w=400&q=85", tag:"WONDERKID"},
  {name:"Niko Vuković",age:16,pos:"CB",region:"Croatia",ovr:64,pot:89,stars:4,img:"https://images.unsplash.com/photo-1521119989659-a83eee488004?auto=format&fit=crop&w=400&q=85", tag:"AI PICK"},
];

export default function Scouting() {
  return <div className="mx-auto max-w-[1500px] animate-in"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="mb-2 flex items-center gap-3"><LivePill>42 scouts active</LivePill><span className="text-[8px] font-bold uppercase tracking-wider text-slate-700">Global database 18,402</span></div><h1 className="font-display text-3xl uppercase italic sm:text-[42px]">Scouting Center</h1><p className="mt-1.5 text-xs text-slate-500">See the future before the football world does.</p></div><Button><Crosshair size={14}/>Launch Assignment</Button></div>
    <div className="stagger mt-6 grid gap-3 sm:grid-cols-3"><StatTile icon={Telescope} label="Players Tracked" value="284" delta="+38 this month" accent="cyan"/><StatTile icon={Sparkles} label="Elite Potential" value="16" delta="90+ projected" accent="gold"/><StatTile icon={Globe2} label="Regions Active" value="08" delta="42 live scouts" accent="lime"/></div>
    <GamePanel className="premium-ring status-scan relative mt-5 overflow-hidden p-5 sm:p-7"><div className="absolute inset-0 opacity-40 [background:radial-gradient(circle_at_50%_50%,rgba(34,211,238,.15),transparent_50%)]"/><div className="relative grid gap-6 lg:grid-cols-[1fr_1.2fr] lg:items-center"><div><p className="text-[8px] font-black uppercase tracking-[.2em] text-cyan-300">Global Talent Radar</p><h2 className="font-display mt-2 text-3xl uppercase italic">8 regions scanning</h2><p className="mt-3 max-w-md text-[10px] leading-5 text-slate-500">AI pattern recognition is monitoring match data, development curves and contract opportunities across your target markets.</p><Button variant="secondary" className="mt-5"><BrainCircuit size={13}/>View AI Recommendations</Button></div><div className="relative mx-auto aspect-square w-full max-w-[360px] rounded-full border border-cyan-300/15 bg-cyan-300/[.025] shadow-[0_0_70px_rgba(34,211,238,.08)]"><div className="absolute inset-[15%] rounded-full border border-cyan-300/10"/><div className="absolute inset-[32%] rounded-full border border-cyan-300/10"/><div className="absolute left-1/2 top-0 h-full w-px bg-cyan-300/10"/><div className="absolute left-0 top-1/2 h-px w-full bg-cyan-300/10"/><div className="absolute inset-[4%] animate-[spin_8s_linear_infinite] rounded-full border-t border-cyan-300/70 shadow-[0_-5px_20px_rgba(34,211,238,.12)]"/><div className="absolute inset-[22%] animate-[spin_12s_linear_infinite_reverse] rounded-full border-b border-[#a3ff12]/25"/>{[[25,35],[66,22],[73,67],[38,78],[53,48]].map(([x,y],i)=><span key={i} className="pulse-live absolute size-2 rounded-full bg-[#a3ff12]" style={{left:`${x}%`,top:`${y}%`}}/>)}<Radar className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 text-cyan-300/40 drop-shadow-[0_0_12px_rgba(34,211,238,.5)]" size={32}/></div></div></GamePanel>
    <section className="mt-6"><SectionHeader kicker="AI Shortlist" title="Future Stars" action={<span className="text-[8px] font-black uppercase text-cyan-300">View 16 prospects →</span>}/><div className="stagger grid gap-4 md:grid-cols-3">{prospects.map(p=><GamePanel key={p.name} className="glass-hover media-cinematic group overflow-hidden"><div className="relative h-48"><Image src={p.img} fill sizes="400px" alt={p.name} className="object-cover opacity-75 grayscale-[15%]"/><div className="absolute inset-0 bg-gradient-to-t from-[#08131e] via-transparent to-transparent"/><span className="absolute left-4 top-4 rounded-md border border-[#a3ff12]/25 bg-black/50 px-2 py-1 text-[7px] font-black tracking-wider text-[#a3ff12] backdrop-blur">{p.tag}</span><div className="absolute bottom-4 left-4"><p className="text-lg font-black uppercase italic">{p.name}</p><p className="mt-1 text-[8px] font-bold text-slate-400">{p.pos} · AGE {p.age} · {p.region.toUpperCase()}</p></div></div><div className="p-4"><div className="grid grid-cols-3 text-center"><div><p className="text-[8px] text-slate-600">CURRENT</p><p className="font-display mt-1 text-xl">{p.ovr}</p></div><div className="border-x border-white/[.07]"><p className="text-[8px] text-slate-600">POTENTIAL</p><p className="font-display mt-1 text-xl text-[#a3ff12]">{p.pot}</p></div><div><p className="text-[8px] text-slate-600">RATING</p><div className="mt-2 flex justify-center">{Array.from({length:p.stars}).map((_,i)=><Star key={i} size={10} fill="currentColor" className="text-amber-300 drop-shadow-[0_0_5px_rgba(247,198,93,.35)]"/>)}</div></div></div><Button variant="secondary" className="mt-4 w-full">Open Scout Report</Button></div></GamePanel>)}</div></section>
  </div>;
}
