import { Crown, Gem, Globe2, Handshake, Lock, Search, Shield, Sparkles, Zap } from "lucide-react";
import { GamePanel, LivePill, Meter, SectionHeader } from "@/components/game-ui";

const badges = [
  {title:"Elite Negotiator",desc:"Win 10 high-pressure negotiations.",progress:100,rarity:"LEGENDARY",icon:Handshake,color:"amber",earned:true},
  {title:"Top Scout",desc:"Discover five 90+ potential players.",progress:80,rarity:"EPIC",icon:Search,color:"cyan",earned:false},
  {title:"Rising Agent",desc:"Reach reputation level 25.",progress:100,rarity:"RARE",icon:Zap,color:"lime",earned:true},
  {title:"Global Connector",desc:"Close deals across 10 countries.",progress:70,rarity:"EPIC",icon:Globe2,color:"cyan",earned:false},
  {title:"Big Deal Closer",desc:"Complete a transfer above €50M.",progress:100,rarity:"LEGENDARY",icon:Gem,color:"amber",earned:true},
  {title:"Talent Hunter",desc:"Sign 20 players under age 21.",progress:65,rarity:"RARE",icon:Shield,color:"lime",earned:false},
];

export default function Achievements() {
  return <div className="mx-auto max-w-[1500px] animate-in"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="mb-2 flex items-center gap-3"><LivePill>38 career level</LivePill><span className="text-[8px] font-bold uppercase tracking-wider text-slate-700">18 / 42 unlocked</span></div><h1 className="font-display text-3xl uppercase italic sm:text-[42px]">Achievements</h1><p className="mt-1.5 text-xs text-slate-500">Your victories, milestones and reputation—made visible.</p></div></div>
    <GamePanel className="premium-ring status-scan relative mt-6 overflow-hidden p-7 pitch-grid"><div className="absolute right-[-6%] top-[-70%] size-[430px] rounded-full border border-amber-300/10"/><div className="relative flex flex-col justify-between gap-7 md:flex-row md:items-center"><div className="flex items-center gap-5"><div className="float-slow relative grid size-24 place-items-center rounded-[28px] border border-amber-300/30 bg-gradient-to-br from-amber-300/15 to-amber-700/5 shadow-[0_0_65px_rgba(247,198,93,.16)]"><Crown size={38} className="text-amber-300 drop-shadow-[0_0_12px_rgba(247,198,93,.5)]"/><Sparkles size={14} className="absolute right-2 top-2 text-amber-200"/></div><div><p className="text-[8px] font-black uppercase tracking-[.2em] text-amber-300">Current Prestige</p><h2 className="font-display mt-1 text-3xl uppercase italic">Elite Agent III</h2><p className="mt-2 text-[9px] text-slate-500">Top 2% of all registered agents</p></div></div><div className="w-full max-w-sm"><div className="flex justify-between text-[8px] font-black uppercase text-slate-500"><span>Prestige progress</span><span>7,240 / 10,000 XP</span></div><div className="mt-3"><Meter value={72} color="gold"/></div><p className="mt-3 text-right text-[8px] text-amber-300">Next: Elite Agent II</p></div></div></GamePanel>
    <section className="mt-6"><SectionHeader kicker="Career Collection" title="Badge Cabinet" action={<span className="text-[8px] font-black text-slate-600">3 LEGENDARY · 8 EPIC · 7 RARE</span>}/><div className="stagger grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{badges.map(b=>{const Icon=b.icon;const glow=b.color==="amber"?"rgba(247,198,93,.25)":b.color==="lime"?"rgba(163,255,18,.22)":"rgba(34,211,238,.22)";return <GamePanel key={b.title} className={`achievement-card glass-hover group relative overflow-hidden p-5 ${!b.earned?"opacity-75 grayscale-[20%]":""}`}><div className={`absolute right-[-30px] top-[-30px] size-28 rounded-full blur-3xl transition duration-500 group-hover:scale-150 ${b.color==="amber"?"bg-amber-300/10":b.color==="lime"?"bg-[#a3ff12]/10":"bg-cyan-300/10"}`}/><div className="relative flex items-start justify-between"><span className={`achievement-icon grid size-14 place-items-center rounded-2xl border ${b.color==="amber"?"border-amber-300/25 bg-amber-300/[.08] text-amber-300":b.color==="lime"?"border-[#a3ff12]/25 bg-[#a3ff12]/[.07] text-[#a3ff12]":"border-cyan-300/25 bg-cyan-300/[.07] text-cyan-300"}`} style={{"--badge-glow":glow} as React.CSSProperties}><Icon size={24}/></span>{b.earned?<span className="rounded-md border border-[#a3ff12]/20 bg-[#a3ff12]/[.07] px-2 py-1 text-[7px] font-black text-[#a3ff12]">UNLOCKED</span>:<Lock size={13} className="text-slate-700"/>}</div><div className="relative mt-5"><p className={`text-[7px] font-black tracking-[.15em] ${b.color==="amber"?"text-amber-300":b.color==="lime"?"text-[#a3ff12]":"text-cyan-300"}`}>{b.rarity}</p><h3 className="mt-1 text-[13px] font-black uppercase italic">{b.title}</h3><p className="mt-2 text-[9px] text-slate-600">{b.desc}</p><div className="mt-5 flex justify-between text-[8px] font-bold text-slate-600"><span>PROGRESS</span><span>{b.progress}%</span></div><div className="mt-2"><Meter value={b.progress} color={b.color==="amber"?"gold":b.color==="lime"?"lime":"cyan"}/></div></div></GamePanel>})}</div></section>
  </div>;
}
