const COUNTRY_CODE_ALIASES: Record<string, string> = {
  AL: "ALB",
  ALG: "ALG",
  AR: "ARG",
  AT: "AUT",
  AU: "AUS",
  BA: "BIH",
  BE: "BEL",
  BF: "BFA",
  BG: "BUL",
  BGR: "BUL",
  BR: "BRA",
  CA: "CAN",
  CD: "COD",
  CH: "SUI",
  CHE: "SUI",
  CHL: "CHI",
  CI: "CIV",
  CL: "CHI",
  CM: "CMR",
  CO: "COL",
  CZ: "CZE",
  DE: "GER",
  DEU: "GER",
  DK: "DEN",
  DNK: "DEN",
  DZ: "ALG",
  DZA: "ALG",
  EC: "ECU",
  EG: "EGY",
  ES: "ESP",
  FR: "FRA",
  GB: "ENG",
  GE: "GEO",
  GH: "GHA",
  GM: "GAM",
  GMB: "GAM",
  GN: "GUI",
  GR: "GRE",
  GRC: "GRE",
  HR: "CRO",
  HRV: "CRO",
  HT: "HAI",
  HTI: "HAI",
  HU: "HUN",
  IE: "IRL",
  IL: "ISR",
  IQ: "IRQ",
  IS: "ISL",
  IT: "ITA",
  JM: "JAM",
  JP: "JPN",
  KR: "KOR",
  MA: "MAR",
  ML: "MLI",
  MX: "MEX",
  MZ: "MOZ",
  NG: "NGA",
  NL: "NED",
  NLD: "NED",
  NO: "NOR",
  NZ: "NZL",
  PL: "POL",
  PR: "PUR",
  PRT: "POR",
  PT: "POR",
  PY: "PAR",
  PRY: "PAR",
  RS: "SRB",
  SE: "SWE",
  SI: "SVN",
  SK: "SVK",
  SL: "SLE",
  SN: "SEN",
  TR: "TUR",
  TT: "TRI",
  TTO: "TRI",
  UA: "UKR",
  US: "USA",
  UY: "URU",
  URY: "URU",
  UZ: "UZB",
  WAL: "WAL",
  WLS: "WAL",
};

const COUNTRY_FLAG_FILES: Record<string, string> = {
  ALG: "dz",
  BUL: "bg",
  CHI: "cl",
  CRO: "hr",
  DEN: "dk",
  ENG: "gb-eng",
  GAM: "gm",
  GER: "de",
  GRE: "gr",
  GUI: "gn",
  HAI: "ht",
  KOR: "kr",
  NED: "nl",
  NIR: "gb-nir",
  PAR: "py",
  POR: "pt",
  SCO: "gb-sct",
  SLE: "sl",
  SUI: "ch",
  TRI: "tt",
  URU: "uy",
  WAL: "gb-wls",
};

const ISO_ALPHA2_TO_ALPHA3 = Object.fromEntries(
  Object.entries(ISO_ALPHA3_TO_ALPHA2).map(([alpha3, alpha2]) => [alpha2.toUpperCase(), alpha3]),
);

const COUNTRY_NAMES: Record<string, string> = {
  albania: "ALB",
  algeria: "ALG",
  argentina: "ARG",
  australia: "AUS",
  austria: "AUT",
  belgium: "BEL",
  "bosnia and herzegovina": "BIH",
  brazil: "BRA",
  bulgaria: "BUL",
  "burkina faso": "BFA",
  cameroon: "CMR",
  canada: "CAN",
  chile: "CHI",
  colombia: "COL",
  croatia: "CRO",
  "czech republic": "CZE",
  czechia: "CZE",
  denmark: "DEN",
  "dr congo": "COD",
  "democratic republic of the congo": "COD",
  ecuador: "ECU",
  egypt: "EGY",
  england: "ENG",
  france: "FRA",
  gambia: "GAM",
  georgia: "GEO",
  germany: "GER",
  ghana: "GHA",
  greece: "GRE",
  guinea: "GUI",
  haiti: "HAI",
  hungary: "HUN",
  iceland: "ISL",
  iraq: "IRQ",
  ireland: "IRL",
  israel: "ISR",
  italy: "ITA",
  "ivory coast": "CIV",
  jamaica: "JAM",
  japan: "JPN",
  "korea republic": "KOR",
  "south korea": "KOR",
  mali: "MLI",
  mexico: "MEX",
  morocco: "MAR",
  mozambique: "MOZ",
  netherlands: "NED",
  "new zealand": "NZL",
  nigeria: "NGA",
  "northern ireland": "NIR",
  norway: "NOR",
  paraguay: "PAR",
  poland: "POL",
  portugal: "POR",
  "republic of ireland": "IRL",
  scotland: "SCO",
  senegal: "SEN",
  serbia: "SRB",
  "sierra leone": "SLE",
  slovakia: "SVK",
  slovenia: "SVN",
  spain: "ESP",
  sweden: "SWE",
  switzerland: "SUI",
  "trinidad and tobago": "TRI",
  turkey: "TUR",
  ukraine: "UKR",
  uruguay: "URU",
  "united states": "USA",
  "united states of america": "USA",
  usa: "USA",
  uzbekistan: "UZB",
  wales: "WAL",
};

function normalizeLookupKey(value?: string | null) {
  return String(value || "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

export function normalizeTouchlineCountryCode3(code?: string | null) {
  const value = String(code || "").trim().toUpperCase();
  return COUNTRY_CODE_ALIASES[value] || ISO_ALPHA2_TO_ALPHA3[value] || value || "N/A";
}

export function touchlineCountryCode3FromName(name?: string | null) {
  return COUNTRY_NAMES[normalizeLookupKey(name)] || null;
}

export function touchlineCountryFlagUrl(code?: string | null) {
  const code3 = normalizeTouchlineCountryCode3(code);
  const flagFile = COUNTRY_FLAG_FILES[code3] || ISO_ALPHA3_TO_ALPHA2[code3];
  return flagFile ? `/touchlineArena/shared/country-flags-4x3/${flagFile}.svg` : null;
}

export function hasTouchlineCountryFlag(code?: string | null) {
  return Boolean(touchlineCountryFlagUrl(code));
}
import { ISO_ALPHA3_TO_ALPHA2 } from "./iso-alpha3-to-alpha2.generated.ts";
