import type { TouchLineLocale } from "./i18n.ts";
import { resolveTouchlineCatalogueLocale } from "./catalogue-locale.ts";
import { getTouchlineTablesPresentationCopy } from "./tables-presentation-i18n.ts";
import { getTouchlineMatchCentreCopy } from "./match-centre-i18n.ts";
import { getTouchlineCoachCardCopy } from "./coach-card-i18n.ts";

const locales = ["en-GB", "pt-BR", "es-ES", "it-IT", "fr-FR", "ar-SA", "tr-TR", "de-DE"] as const;
// Column order follows locales. Six additional languages remain review-only drafts.
const rows = {
  title: ["Official League Table", "Tabela Oficial da Liga", "Clasificación oficial de la liga", "Classifica ufficiale della lega", "Classement officiel de la ligue", "جدول ترتيب الدوري الرسمي", "Resmî lig tablosu", "Offizielle Ligatabelle"],
  description: ["The one official table combines TouchLine Verified final results with the latest persisted live scores. Live rows and positions are provisional until full time.", "A única tabela oficial combina resultados finais verificados com os últimos placares ao vivo persistidos. Linhas e posições ao vivo são provisórias até o fim.", "La única clasificación oficial combina los resultados finales verificados por TouchLine Verified con los últimos marcadores en directo guardados. Las filas y posiciones en directo son provisionales hasta el final.", "L’unica classifica ufficiale combina i risultati finali verificati da TouchLine Verified con gli ultimi punteggi live salvati. Righe e posizioni live sono provvisorie fino al termine.", "Le classement officiel unique combine les résultats finaux vérifiés par TouchLine Verified et les derniers scores en direct enregistrés. Les lignes et positions en direct sont provisoires jusqu’à la fin du match.", "يجمع جدول الترتيب الرسمي الوحيد بين النتائج النهائية المتحقق منها عبر TouchLine Verified وآخر النتائج المباشرة المحفوظة. الصفوف والمراكز المباشرة مؤقتة حتى نهاية المباراة.", "Tek resmî tablo, TouchLine Verified tarafından doğrulanmış kesin sonuçları kaydedilmiş en son canlı skorlarla birleştirir. Canlı satırlar ve sıralamalar maç sonuna kadar geçicidir.", "Die einzige offizielle Tabelle kombiniert von TouchLine Verified verifizierte Endergebnisse mit den zuletzt gespeicherten Live-Spielständen. Live-Zeilen und Platzierungen sind bis zum Abpfiff vorläufig."],
  caption: ["TouchLine England official league table", "Tabela oficial da liga TouchLine England", "Clasificación oficial de la liga TouchLine England", "Classifica ufficiale della lega TouchLine England", "Classement officiel de la ligue TouchLine England", "جدول ترتيب دوري TouchLine England الرسمي", "TouchLine England resmî lig tablosu", "Offizielle Ligatabelle von TouchLine England"],
  position: ["Pos", "Pos", "Pos", "Pos", "Pos", "المركز", "Sıra", "Pl."],
  club: ["Club", "Clube", "Club", "Club", "Club", "النادي", "Kulüp", "Verein"],
  played: ["P", "J", "PJ", "G", "MJ", "لعب", "O", "Sp."],
  goalsFor: ["GF", "GF", "GF", "GF", "BP", "له", "AG", "T"],
  goalsAgainst: ["GA", "GA", "GC", "GS", "BC", "عليه", "YG", "GT"],
  difference: ["GD", "SG", "DG", "DR", "Diff", "الفارق", "AV", "Diff."],
  points: ["Pts", "Pts", "Pts", "Pt", "Pts", "النقاط", "P", "Pkt."],
  form: ["Form", "Forma", "Forma", "Forma", "Forme", "الأداء الأخير", "Form", "Form"],
  stale: ["STALE", "DESATUALIZADO", "DESACTUALIZADO", "NON AGGIORNATO", "NON ACTUALISÉ", "غير محدّث", "GÜNCEL DEĞİL", "VERALTET"],
  scoreUnavailable: ["score unavailable", "placar indisponível", "marcador no disponible", "punteggio non disponibile", "score indisponible", "النتيجة غير متاحة", "skor kullanılamıyor", "Spielstand nicht verfügbar"],
  finalResults: ["verified final results", "resultados finais verificados", "resultados finales verificados", "risultati finali verificati", "résultats finaux vérifiés", "نتائج نهائية متحقق منها", "doğrulanmış kesin sonuçlar", "verifizierte Endergebnisse"],
  seasonStatus: ["Season status", "Status da temporada", "Estado de la temporada", "Stato della stagione", "État de la saison", "حالة الموسم", "Sezon durumu", "Saisonstatus"],
  seasonLive: ["Live · provisional", "Ao vivo · provisória", "En directo · provisional", "Live · provvisoria", "En direct · provisoire", "مباشر · مؤقت", "Canlı · geçici", "Live · vorläufig"],
  seasonVerified: ["Verified through latest final", "Verificada até o último resultado final", "Verificada hasta el último resultado final", "Verificata fino all’ultimo risultato finale", "Vérifié jusqu’au dernier résultat final", "متحقق منها حتى آخر نتيجة نهائية", "Son kesin sonuca kadar doğrulandı", "Bis zum letzten Endergebnis verifiziert"],
  seasonInitial: ["Initial standings", "Tabela inicial", "Clasificación inicial", "Classifica iniziale", "Classement initial", "الترتيب الأولي", "Başlangıç sıralaması", "Anfangstabelle"],
  seasonChecking: ["Integrity check", "Verificação de integridade", "Verificación de integridad", "Verifica dell’integrità", "Vérification de l’intégrité", "التحقق من سلامة البيانات", "Bütünlük kontrolü", "Integritätsprüfung"],
  pendingTitle: ["Initial table — all 20 clubs are level.", "Tabela inicial — os 20 clubes estão empatados.", "Clasificación inicial: los 20 clubes están empatados.", "Classifica iniziale: tutti i 20 club sono a pari merito.", "Classement initial : les 20 clubs sont à égalité.", "الجدول الأولي — الأندية العشرون متساوية.", "Başlangıç tablosu — 20 kulübün tamamı eşit.", "Anfangstabelle — alle 20 Vereine sind gleichauf."],
  pendingDescription: ["Every club is level on sporting criteria. Continuous positions use alphabetical display order only until a verified result separates them.", "Todos os clubes estão empatados nos critérios esportivos. As posições contínuas usam ordem alfabética apenas para apresentação até que um resultado verificado os separe.", "Todos los clubes están empatados según los criterios deportivos. Las posiciones consecutivas usan el orden alfabético solo para mostrarlos hasta que un resultado verificado los separe.", "Tutti i club sono a pari merito secondo i criteri sportivi. Le posizioni consecutive seguono l’ordine alfabetico solo per la visualizzazione finché un risultato verificato non li separa.", "Tous les clubs sont à égalité selon les critères sportifs. Les positions consécutives suivent l’ordre alphabétique uniquement pour l’affichage, jusqu’à ce qu’un résultat vérifié les départage.", "جميع الأندية متساوية وفق المعايير الرياضية. تستخدم المراكز المتتابعة الترتيب الأبجدي للعرض فقط حتى تفصل بينها نتيجة متحقق منها.", "Tüm kulüpler sportif ölçütlere göre eşittir. Doğrulanmış bir sonuç onları ayırana kadar ardışık sıralar yalnızca gösterim için alfabetik düzen kullanır.", "Alle Vereine sind nach sportlichen Kriterien gleichauf. Fortlaufende Platzierungen verwenden nur zur Anzeige die alphabetische Reihenfolge, bis ein verifiziertes Ergebnis sie trennt."],
  partialTitle: ["Verified results remain visible; league positions are temporarily withheld.", "Os resultados verificados continuam visíveis; as posições estão temporariamente suspensas.", "Los resultados verificados siguen visibles; las posiciones se ocultan temporalmente.", "I risultati verificati restano visibili; le posizioni sono temporaneamente sospese.", "Les résultats vérifiés restent visibles ; les positions sont temporairement masquées.", "تبقى النتائج المتحقق منها ظاهرة؛ وتُحجب مراكز الدوري مؤقتًا.", "Doğrulanmış sonuçlar görünür kalır; lig sıralamaları geçici olarak gizlenir.", "Verifizierte Ergebnisse bleiben sichtbar; die Platzierungen werden vorübergehend zurückgehalten."],
  partialDescription: ["TouchLine detected a duplicated fixture observation. No position is published until table integrity is restored.", "A TouchLine detectou uma observação duplicada de fixture. Nenhuma posição é publicada até a integridade da tabela ser restaurada.", "TouchLine detectó una observación duplicada de un partido. No se publica ninguna posición hasta restaurar la integridad de la clasificación.", "TouchLine ha rilevato un’osservazione duplicata di una partita. Nessuna posizione viene pubblicata finché l’integrità della classifica non è ripristinata.", "TouchLine a détecté une observation de match en double. Aucune position n’est publiée avant le rétablissement de l’intégrité du classement.", "رصد TouchLine سجل رصد مكررًا لمباراة. لا يُنشر أي مركز حتى استعادة سلامة جدول الترتيب.", "TouchLine yinelenen bir maç gözlemi tespit etti. Tablo bütünlüğü sağlanana kadar sıralama yayımlanmaz.", "TouchLine hat eine doppelte Spielbeobachtung erkannt. Bis zur Wiederherstellung der Tabellenintegrität wird keine Platzierung veröffentlicht."],
  unavailableTitle: ["Official standings are temporarily unavailable.", "A tabela oficial está temporariamente indisponível.", "La clasificación oficial no está disponible temporalmente.", "La classifica ufficiale è temporaneamente indisponibile.", "Le classement officiel est temporairement indisponible.", "الترتيب الرسمي غير متاح مؤقتًا.", "Resmî sıralama geçici olarak kullanılamıyor.", "Die offizielle Tabelle ist vorübergehend nicht verfügbar."],
  unavailableDescription: ["No league position is shown until TouchLine can verify the canonical result set again.", "Nenhuma posição é exibida até a TouchLine verificar novamente o conjunto canônico de resultados.", "No se muestra ninguna posición hasta que TouchLine pueda verificar de nuevo el conjunto canónico de resultados.", "Nessuna posizione viene mostrata finché TouchLine non può verificare nuovamente l’insieme canonico dei risultati.", "Aucune position n’est affichée tant que TouchLine ne peut pas vérifier à nouveau l’ensemble canonique des résultats.", "لا يُعرض أي مركز في الدوري حتى يتمكن TouchLine من التحقق مجددًا من مجموعة النتائج المرجعية.", "TouchLine esas sonuç kümesini yeniden doğrulayana kadar lig sıralaması gösterilmez.", "Es wird keine Platzierung angezeigt, bis TouchLine den maßgeblichen Ergebnissatz erneut verifizieren kann."],
  integrityTitle: ["Official standings are being checked.", "A tabela oficial está sendo verificada.", "Se está verificando la clasificación oficial.", "La classifica ufficiale è in fase di verifica.", "Le classement officiel est en cours de vérification.", "جارٍ التحقق من الترتيب الرسمي.", "Resmî sıralama kontrol ediliyor.", "Die offizielle Tabelle wird geprüft."],
  integrityDescription: ["TouchLine found an identity or season consistency issue, so no league position is published.", "A TouchLine encontrou uma inconsistência de identidade ou temporada; nenhuma posição é publicada.", "TouchLine encontró una inconsistencia de identidad o temporada; no se publica ninguna posición.", "TouchLine ha riscontrato un’incoerenza di identità o stagione; nessuna posizione viene pubblicata.", "TouchLine a détecté une incohérence d’identité ou de saison ; aucune position n’est publiée.", "وجد TouchLine مشكلة في اتساق الهوية أو الموسم، لذلك لا يُنشر أي مركز في الدوري.", "TouchLine kimlik veya sezon tutarlılığı sorunu buldu; bu nedenle lig sıralaması yayımlanmaz.", "TouchLine hat eine Unstimmigkeit bei Identität oder Saison gefunden; daher wird keine Platzierung veröffentlicht."],
  scrollLabel: ["Scrollable league table, 20 clubs", "Tabela rolável da liga, 20 clubes", "Clasificación de liga desplazable, 20 clubes", "Classifica della lega scorrevole, 20 club", "Classement de ligue défilant, 20 clubs", "جدول ترتيب دوري قابل للتمرير، 20 ناديًا", "Kaydırılabilir lig tablosu, 20 kulüp", "Scrollbare Ligatabelle, 20 Vereine"],
} as const satisfies Record<string, readonly [string, string, string, string, string, string, string, string]>;

type OwnCopy = Readonly<Record<keyof typeof rows, string>>;
export type TouchlineOfficialLeagueTableCopy = OwnCopy & Readonly<Record<"eyebrow" | "won" | "drawn" | "lost" | "live" | "currentClub", string>>;
export const TOUCHLINE_OFFICIAL_LEAGUE_TABLE_DRAFT_LOCALES = ["es-ES", "it-IT", "fr-FR", "ar-SA", "tr-TR", "de-DE"] as const;
export const TOUCHLINE_OFFICIAL_LEAGUE_TABLE_DRAFT_STATUS = "draft" as const;
export const TOUCHLINE_OFFICIAL_LEAGUE_TABLE_CATALOGUES = Object.fromEntries(locales.map((locale, index) => [
  locale, Object.fromEntries(Object.entries(rows).map(([key, values]) => [key, values[index]])),
])) as Record<TouchLineLocale, OwnCopy>;

export function getTouchlineOfficialLeagueTableCopy(locale?: string | null, draftLocalesEnabled = false): TouchlineOfficialLeagueTableCopy {
  const resolved = resolveTouchlineCatalogueLocale(locale, draftLocalesEnabled);
  const table = getTouchlineTablesPresentationCopy(resolved, draftLocalesEnabled);
  const match = getTouchlineMatchCentreCopy(resolved, draftLocalesEnabled);
  const coach = getTouchlineCoachCardCopy(resolved, draftLocalesEnabled);
  return { ...TOUCHLINE_OFFICIAL_LEAGUE_TABLE_CATALOGUES[resolved], eyebrow: "TouchLine England League",
    won: table.winsShort, drawn: table.drawsShort, lost: table.lossesShort, live: match.liveNow, currentClub: coach.currentClub };
}
