import type { TouchLineLocale } from "./i18n.ts";
import { resolveTouchlineCatalogueLocale } from "./catalogue-locale.ts";

const locales = ["en-GB", "pt-BR", "es-ES", "it-IT", "fr-FR", "ar-SA", "tr-TR", "de-DE"] as const;
type Translations = readonly [string, string, string, string, string, string, string, string];
/** Copy for existing profile posts only. Demo admission, facts, IDs and ordering
 * remain in the route. Six extra languages are drafts, not a release gate. */
const rows = {
  publishedTitle: ["Editorial card profile published", "Perfil editorial do card publicado", "Perfil editorial de la tarjeta publicado", "Profilo editoriale della carta pubblicato", "Profil éditorial de la carte publié", "تم نشر الملف التحريري للبطاقة", "Kartın editoryal profili yayımlandı", "Redaktionelles Kartenprofil veröffentlicht"],
  cardTitle: ["TouchLine card profile", "Perfil do card TouchLine", "Perfil de la tarjeta TouchLine", "Profilo della carta TouchLine", "Profil de la carte TouchLine", "ملف بطاقة TouchLine", "TouchLine kart profili", "TouchLine-Kartenprofil"],
  editorialBody: ["The tier appears when the editorial team publishes this card.", "O tier aparece quando a equipa editorial publica este card.", "El tier aparece cuando el equipo editorial publica esta tarjeta.", "Il tier appare quando la redazione pubblica questa carta.", "Le tier apparaît lorsque l’équipe éditoriale publie cette carte.", "يظهر tier عندما ينشر الفريق التحريري هذه البطاقة.", "Tier, editoryal ekip bu kartı yayımladığında görünür.", "Der tier erscheint, wenn das Redaktionsteam diese Karte veröffentlicht."],
  totalRatingSuffix: ["total rating", "nota total", "valoración total", "valutazione totale", "note totale", "التقييم الإجمالي", "toplam puan", "Gesamtbewertung"],
  cardTier: ["Card tier", "Tier do card", "Tier de la tarjeta", "Tier della carta", "Tier de la carte", "Tier البطاقة", "Kart tier", "Karten-tier"],
  officialUpdated: ["Official player data updated", "Dados oficiais do atleta atualizados", "Datos oficiales del jugador actualizados", "Dati ufficiali del giocatore aggiornati", "Données officielles du joueur mises à jour", "تم تحديث البيانات الرسمية للاعب", "Oyuncunun resmî verileri güncellendi", "Offizielle Spielerdaten aktualisiert"],
  officialUnavailable: ["Additional official data unavailable", "Dados oficiais adicionais indisponíveis", "Datos oficiales adicionales no disponibles", "Dati ufficiali aggiuntivi non disponibili", "Données officielles supplémentaires indisponibles", "البيانات الرسمية الإضافية غير متاحة", "Ek resmî veriler kullanılamıyor", "Zusätzliche offizielle Daten nicht verfügbar"],
  verifiedBody: ["Verified football profile for {playerName}. Match events will be published here without revealing any ClubOwner strategy.", "Perfil esportivo verificado para {playerName}. Eventos de partida serão publicados aqui sem revelar qualquer estratégia de ClubOwner.", "Perfil futbolístico verificado de {playerName}. Los eventos del partido se publicarán aquí sin revelar ninguna estrategia de ClubOwner.", "Profilo calcistico verificato di {playerName}. Gli eventi della partita saranno pubblicati qui senza rivelare alcuna strategia di ClubOwner.", "Profil football vérifié de {playerName}. Les événements du match seront publiés ici sans révéler aucune stratégie de ClubOwner.", "ملف كروي موثّق لـ {playerName}. ستُنشر أحداث المباراة هنا دون الكشف عن أي استراتيجية لـ ClubOwner.", "{playerName} için doğrulanmış futbol profili. Maç olayları, ClubOwner stratejileri açıklanmadan burada yayımlanacak.", "Verifiziertes Fußballprofil von {playerName}. Spielereignisse werden hier veröffentlicht, ohne ClubOwner-Strategien offenzulegen."],
  waitingBody: ["The feed waits for verified data before publishing performance, injuries or match events.", "O feed aguardará dados verificados antes de publicar desempenho, lesões ou acontecimentos da partida.", "El feed espera datos verificados antes de publicar rendimiento, lesiones o eventos del partido.", "Il feed attende dati verificati prima di pubblicare prestazioni, infortuni o eventi della partita.", "Le fil attend des données vérifiées avant de publier des performances, des blessures ou des événements du match.", "ينتظر الموجز بيانات موثّقة قبل نشر الأداء أو الإصابات أو أحداث المباراة.", "Akış; performans, sakatlık veya maç olaylarını yayımlamadan önce doğrulanmış verileri bekler.", "Der Feed wartet auf verifizierte Daten, bevor Leistungen, Verletzungen oder Spielereignisse veröffentlicht werden."],
  officialProfile: ["Official profile", "Perfil oficial", "Perfil oficial", "Profilo ufficiale", "Profil officiel", "الملف الرسمي", "Resmî profil", "Offizielles Profil"],
  position: ["Position", "Posição", "Posición", "Posizione", "Poste", "المركز", "Pozisyon", "Position"],
  country: ["Country", "País", "País", "Paese", "Pays", "البلد", "Ülke", "Land"],
  verification: ["Verification", "Verificação", "Verificación", "Verifica", "Vérification", "التحقق", "Doğrulama", "Verifizierung"],
  verified: ["Verified by TouchLine", "TouchLine Verified", "Verificado por TouchLine", "Verificato da TouchLine", "Vérifié par TouchLine", "موثّق من TouchLine", "TouchLine tarafından doğrulandı", "Von TouchLine verifiziert"],
  fullTimeTitle: ["Full time: outstanding display from {playerName}", "Fim de jogo: grande atuação de {playerName}", "Final del partido: gran actuación de {playerName}", "Fine partita: grande prestazione di {playerName}", "Fin du match : belle prestation de {playerName}", "نهاية المباراة: أداء رائع من {playerName}", "Maç sonu: {playerName} harika bir performans sergiledi", "Abpfiff: starke Leistung von {playerName}"],
  fullTimeBody: ["Example of an automatic full-time post with the verified TouchLine rating.", "Exemplo de publicação automática após o encerramento da partida com a nota TouchLine verificada.", "Ejemplo de publicación automática al finalizar el partido con la valoración TouchLine verificada.", "Esempio di post automatico a fine partita con la valutazione TouchLine verificata.", "Exemple de publication automatique en fin de match avec la note TouchLine vérifiée.", "مثال على منشور تلقائي بعد نهاية المباراة يتضمن تقييم TouchLine الموثّق.", "Doğrulanmış TouchLine puanıyla otomatik maç sonu gönderisi örneği.", "Beispiel eines automatischen Beitrags nach Abpfiff mit verifizierter TouchLine-Bewertung."],
  afterMatch: ["Demo · after the match", "Demonstração · após a partida", "Demostración · después del partido", "Demo · dopo la partita", "Démonstration · après le match", "عرض توضيحي · بعد المباراة", "Demo · maçtan sonra", "Demo · nach dem Spiel"],
  fullTimeBadge: ["Rating 8.7 · simulated total rating 38.0", "Nota 8,7 · nota total simulada 38,0", "Valoración 8.7 · valoración total simulada 38.0", "Valutazione 8.7 · valutazione totale simulata 38.0", "Note 8.7 · note totale simulée 38.0", "تقييم 8.7 · تقييم إجمالي تجريبي 38.0", "Puan 8.7 · simüle edilen toplam puan 38.0", "Bewertung 8.7 · simulierte Gesamtbewertung 38.0"],
  rating: ["Rating", "Nota", "Valoración", "Valutazione", "Note", "التقييم", "Puan", "Bewertung"],
  minutes: ["Minutes", "Minutos", "Minutos", "Minuti", "Minutes", "الدقائق", "Dakika", "Minuten"],
  totalRating: ["Total rating", "Nota total", "Valoración total", "Valutazione totale", "Note totale", "التقييم الإجمالي", "Toplam puan", "Gesamtbewertung"],
  goalTitle: ["{playerName} scored for {clubName}", "{playerName} marcou para o {clubName}", "{playerName} marcó para {clubName}", "{playerName} ha segnato per {clubName}", "{playerName} a marqué pour {clubName}", "سجّل {playerName} لصالح {clubName}", "{playerName}, {clubName} adına gol attı", "{playerName} traf für {clubName}"],
  goalBody: ["The TouchLine Verified goal update generates this communication automatically for every follower of the player.", "A atualização de gol verificada pela TouchLine gera esta comunicação automaticamente para todos os seguidores do atleta.", "La actualización de gol TouchLine Verified genera esta comunicación automáticamente para todos los seguidores del jugador.", "L’aggiornamento del gol TouchLine Verified genera automaticamente questa comunicazione per tutti i follower del giocatore.", "L’actualisation du but TouchLine Verified génère automatiquement cette communication pour tous les abonnés du joueur.", "يُنشئ تحديث الهدف TouchLine Verified هذا الإشعار تلقائيًا لجميع متابعي اللاعب.", "TouchLine Verified gol güncellemesi, oyuncunun tüm takipçileri için bu bildirimi otomatik oluşturur.", "Die TouchLine Verified-Toraktualisierung erzeugt diese Mitteilung automatisch für alle Follower des Spielers."],
  goalMeta: ["Demo · 67 minutes", "Demonstração · 67 minutos", "Demostración · 67 minutos", "Demo · 67 minuti", "Démonstration · 67 minutes", "عرض توضيحي · 67 دقيقة", "Demo · 67 dakika", "Demo · 67 Minuten"],
  goalBadge: ["1 goal · verified TouchLine rating", "1 gol · nota TouchLine verificada", "1 gol · valoración TouchLine verificada", "1 gol · valutazione TouchLine verificata", "1 but · note TouchLine vérifiée", "هدف واحد · تقييم TouchLine موثّق", "1 gol · doğrulanmış TouchLine puanı", "1 Tor · verifizierte TouchLine-Bewertung"],
  goals: ["Goals", "Gols", "Goles", "Gol", "Buts", "الأهداف", "Goller", "Tore"],
  minute: ["Minute", "Minuto", "Minuto", "Minuto", "Minute", "الدقيقة", "Dakika", "Minute"],
  tierTitle: ["The editorial team updated the card tier", "A equipa editorial atualizou o tier do card", "El equipo editorial actualizó el tier de la tarjeta", "La redazione ha aggiornato il tier della carta", "L’équipe éditoriale a mis à jour le tier de la carte", "حدّث الفريق التحريري tier البطاقة", "Editoryal ekip kartın tier bilgisini güncelledi", "Das Redaktionsteam hat den Karten-tier aktualisiert"],
  tierBody: ["Visual example of an editorial change independent of any valuation.", "Exemplo visual de uma alteração editorial independente de qualquer valuation.", "Ejemplo visual de un cambio editorial independiente de cualquier valuation.", "Esempio visivo di una modifica editoriale indipendente da qualsiasi valuation.", "Exemple visuel d’une modification éditoriale indépendante de toute valuation.", "مثال مرئي على تغيير تحريري مستقل عن أي valuation.", "Herhangi bir valuation değerinden bağımsız editoryal değişikliğin görsel örneği.", "Visuelles Beispiel einer redaktionellen Änderung unabhängig von jeder valuation."],
  tierMeta: ["Demo · editorial review", "Demonstração · revisão editorial", "Demostración · revisión editorial", "Demo · revisione editoriale", "Démonstration · révision éditoriale", "عرض توضيحي · مراجعة تحريرية", "Demo · editoryal inceleme", "Demo · redaktionelle Prüfung"],
  tierUpdated: ["Tier updated", "Categoria atualizada", "Tier actualizado", "Tier aggiornato", "Tier mis à jour", "تم تحديث tier", "Tier güncellendi", "Tier aktualisiert"],
  progress: ["Progress", "Evolução", "Evolución", "Evoluzione", "Progression", "التطور", "Gelişim", "Entwicklung"],
  confirmed: ["Confirmed", "Confirmada", "Confirmada", "Confermata", "Confirmée", "مؤكد", "Doğrulandı", "Bestätigt"],
  upgradeStatus: ["Status", "Status", "Estado", "Stato", "Statut", "الحالة", "Durum", "Status"],
  upgraded: ["Upgraded", "Evoluiu", "Mejorado", "Migliorata", "Améliorée", "تمت الترقية", "Geliştirildi", "Verbessert"],
  availabilityTitle: ["Player availability update", "Atualização de disponibilidade do atleta", "Actualización de disponibilidad del jugador", "Aggiornamento sulla disponibilità del giocatore", "Mise à jour de la disponibilité du joueur", "تحديث جاهزية اللاعب", "Oyuncunun uygunluk durumu güncellemesi", "Aktualisierung der Spielerverfügbarkeit"],
  availabilityBody: ["When TouchLine verifies an injury, suspension or doubt for the next match, followers receive an update like this.", "Quando a TouchLine verificar lesão, suspensão ou dúvida para a próxima partida, os seguidores recebem uma atualização como esta.", "Cuando TouchLine verifica una lesión, suspensión o duda para el próximo partido, los seguidores reciben una actualización como esta.", "Quando TouchLine verifica un infortunio, una squalifica o un dubbio per la prossima partita, i follower ricevono un aggiornamento come questo.", "Lorsque TouchLine vérifie une blessure, une suspension ou une incertitude pour le prochain match, les abonnés reçoivent une actualisation comme celle-ci.", "عندما تتحقق TouchLine من إصابة أو إيقاف أو شك في الجاهزية للمباراة المقبلة، يتلقى المتابعون تحديثًا كهذا.", "TouchLine bir sakatlığı, cezayı veya sonraki maç için belirsizliği doğruladığında takipçiler böyle bir güncelleme alır.", "Wenn TouchLine eine Verletzung, Sperre oder einen fraglichen Einsatz im nächsten Spiel bestätigt, erhalten Follower eine solche Aktualisierung."],
  availabilityMeta: ["Demo · football alert", "Demonstração · alerta esportivo", "Demostración · alerta futbolística", "Demo · avviso calcistico", "Démonstration · alerte football", "عرض توضيحي · تنبيه كروي", "Demo · futbol uyarısı", "Demo · Fußballhinweis"],
  availabilityBadge: ["Simulated status · awaiting confirmation", "Situação simulada · aguardando confirmação", "Estado simulado · pendiente de confirmación", "Stato simulato · in attesa di conferma", "Statut simulé · en attente de confirmation", "حالة تجريبية · بانتظار التأكيد", "Simüle edilen durum · doğrulama bekleniyor", "Simulierter Status · Bestätigung ausstehend"],
  availability: ["Availability", "Disponibilidade", "Disponibilidad", "Disponibilità", "Disponibilité", "الجاهزية", "Uygunluk", "Verfügbarkeit"],
  attention: ["ATTENTION", "ATENÇÃO", "ATENCIÓN", "ATTENZIONE", "ATTENTION", "تنبيه", "DİKKAT", "ACHTUNG"],
  status: ["Status", "Situação", "Estado", "Stato", "Statut", "الحالة", "Durum", "Status"],
  doubt: ["Doubt", "Dúvida", "Duda", "In dubbio", "Incertain", "غير مؤكد", "Belirsiz", "Fraglich"],
  source: ["Source", "Fonte", "Fuente", "Fonte", "Source", "المصدر", "Kaynak", "Quelle"],
  official: ["Official", "Oficial", "Oficial", "Ufficiale", "Officiel", "رسمي", "Resmî", "Offiziell"],
  nextStep: ["Next step", "Próximo passo", "Próximo paso", "Passaggio successivo", "Prochaine étape", "الخطوة التالية", "Sonraki adım", "Nächster Schritt"],
  review: ["Review", "Revisão", "Revisión", "Revisione", "Révision", "مراجعة", "İnceleme", "Prüfung"],
} as const satisfies Record<string, Translations>;

export type TouchlinePlayerProfileFeedCopy = Readonly<Record<keyof typeof rows, string>>;
export const TOUCHLINE_PLAYER_PROFILE_FEED_DRAFT_STATUS = "draft" as const;
export const TOUCHLINE_PLAYER_PROFILE_FEED_DRAFT_LOCALES = ["es-ES", "it-IT", "fr-FR", "ar-SA", "tr-TR", "de-DE"] as const;
export const TOUCHLINE_PLAYER_PROFILE_FEED_CATALOGUES = Object.fromEntries(locales.map((locale, index) => [locale,
  Object.fromEntries(Object.entries(rows).map(([key, values]) => [key, values[index]])),
])) as Readonly<Record<TouchLineLocale, TouchlinePlayerProfileFeedCopy>>;
export function getTouchlinePlayerProfileFeedCopy(locale?: string | null, draftLocalesEnabled = false): TouchlinePlayerProfileFeedCopy {
  return TOUCHLINE_PLAYER_PROFILE_FEED_CATALOGUES[resolveTouchlineCatalogueLocale(locale, draftLocalesEnabled)];
}
export function formatTouchlinePlayerProfileFeedText(template: string, values: Readonly<{ playerName: string; clubName?: string }>): string {
  return template.replace(/\{(playerName|clubName)\}/g, (token, key: "playerName" | "clubName") => values[key] ?? token);
}
