import { BadgeEuro, Check, Goal, Medal, Target, Trophy, UserPlus, Zap } from "lucide-react";
import { GamePanel, LivePill, Meter, SectionHeader } from "@/components/game-ui";

const objectives = [
  {title:"Close 3 Transfer Deals",desc:"Complete three permanent transfers this month.",progress:67,current:"2 / 3",reward:"1,500 XP",icon:Zap,color:"lime"},
  {title:"Revenue Architect",desc:"Generate €500,000 in agency fees.",progress:82,current:"€412K / €500K",reward:"2,000 XP",icon:BadgeEuro,color:"gold"},
  {title:"Future Star",desc:"Sign one player with 90+ potential.",progress:15,current:"0 / 1",reward:"Elite Scout Pack",icon:UserPlus,color:"cyan"},
  {title:"Career Launch",desc:"Promote a youth player to a top-five league.",progress:45,current:"2 / 5 steps",reward:"3,000 XP",icon:Trophy,color:"cyan"},
  {title:"Global Climb",desc:"Reach the top 150 agent rankings.",progress:78,current:"#184 / #150",reward:"Icon Badge",icon:Medal,color:"gold"},
  {title:"Perfect Window",desc:"Close every active negotiation successfully.",progress:40,current:"2 / 5 deals",reward:"5,000 XP",icon:Goal,color:"lime"},
];

export default function Objectives() {
  return <div className="mx-auto max-w-[1500px] animate-in"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="mb-2 flex items-center gap-3"><LivePill>Season objectives active</LivePill><span className="text-[8px] font-bold uppercase tracking-wider text-slate-700">22 days remaining</span></div><h1 className="font-display text-3xl uppercase italic sm:text-[42px]">Objectives</h1><p className="mt-1.5 text-xs text-slate-500">Every move builds your reputation. Every target shapes your legacy.</p></div></div>
    <GamePanel className="relative mt-6 overflow-hidden p-6 pitch-grid"><div className="relative flex flex-col justify-between gap-6 md:flex-row md:items-center"><div><p className="text-[8px] font-black uppercase tracking-[.2em] text-[#a3ff12]">Monthly Campaign</p><h2 className="font-display mt-2 text-3xl uppercase italic">Summer Power Play</h2><p className="mt-2 text-[9px] text-slate-500">Complete all six objectives to unlock the exclusive Global Power Broker achievement.</p></div><div className="flex items-center gap-5"><div className="relative grid size-24 place-items-center rounded-full border-[6px] border-cyan-300/15"><div className="absolute inset-[-6px] rounded-full border-[6px] border-transparent border-t-[#a3ff12] border-r-[#a3ff12] rotate-45"/><div className="text-center"><p className="font-display text-2xl">54%</p><p className="text-[7px] text-slate-600">COMPLETE</p></div></div><div><p className="text-[8px] text-slate-600">TOTAL REWARDS</p><p className="mt-1 text-lg font-black text-amber-300">12,500 XP</p><p className="mt-1 text-[8px] text-cyan-300">+ 3 EXCLUSIVE ITEMS</p></div></div></div></GamePanel>
    <section className="mt-6"><SectionHeader kicker="Active Challenges" title="Career Targets"/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{objectives.map((o,index)=>{const Icon=o.icon as typeof Zap;return <GamePanel key={o.title} className="glass-hover p-5"><div className="flex items-start justify-between"><span className="grid size-10 place-items-center rounded-xl border border-cyan-300/15 bg-cyan-300/[.06] text-cyan-300"><Icon size={17}/></span><span className="text-[8px] font-black text-amber-300">{o.reward}</span></div><h3 className="mt-5 text-[12px] font-black uppercase italic">{o.title}</h3><p className="mt-2 min-h-9 text-[9px] leading-4 text-slate-600">{o.desc}</p><div className="mt-5 flex justify-between text-[8px] font-bold"><span className="text-slate-500">{o.current}</span><span className="text-slate-300">{o.progress}%</span></div><div className="mt-2"><Meter value={o.progress} color={o.color as "lime"|"gold"|"cyan"}/></div><div className="mt-4 flex items-center justify-between border-t border-white/[.06] pt-3"><span className="text-[7px] font-black uppercase tracking-wider text-slate-700">Objective {String(index+1).padStart(2,"0")}</span>{o.progress===100?<Check size={13} className="text-[#a3ff12]"/>:<Target size={13} className="text-slate-700"/>}</div></GamePanel>})}</div></section>
  </div>;
}
