import Image from "next/image";
import { ArrowUpRight, Building, CircleDollarSign, Globe2, Landmark, ShieldCheck, TrendingUp, Users } from "lucide-react";
import { Button } from "@/components/ui";
import { GamePanel, LivePill, Meter, SectionHeader, StatTile } from "@/components/game-ui";

const opportunities = [
  {title:"Iberia Youth Development Fund",type:"ACADEMY FUND",region:"Spain · Portugal",target:"€2.5M",raised:68,return:"18–24%",risk:"MEDIUM",image:"https://images.unsplash.com/photo-1526232761682-d26e03ac148e?auto=format&fit=crop&w=800&q=85"},
  {title:"NextGen Player Pathway",type:"TALENT DEVELOPMENT",region:"West Africa",target:"€1.2M",raised:84,return:"22–31%",risk:"HIGH",image:"https://images.unsplash.com/photo-1543351611-58f69d7c1781?auto=format&fit=crop&w=800&q=85"},
  {title:"Elite Recovery Lab",type:"PERFORMANCE",region:"United Kingdom",target:"€4.0M",raised:46,return:"12–16%",risk:"LOW",image:"https://images.unsplash.com/photo-1518604666860-9ed391f76460?auto=format&fit=crop&w=800&q=85"},
];

export default function Investors() {
  return <div className="mx-auto max-w-[1500px] animate-in"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="mb-2 flex items-center gap-3"><LivePill>€38.4M capital active</LivePill><span className="text-[8px] font-bold uppercase tracking-wider text-slate-700">126 verified partners</span></div><h1 className="font-display text-3xl uppercase italic sm:text-[42px]">Investor Hub</h1><p className="mt-1.5 text-xs text-slate-500">Capital meets football opportunity—securely, intelligently and transparently.</p></div><Button><Landmark size={14}/>Create Partnership</Button></div>
    <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatTile icon={CircleDollarSign} label="Capital Deployed" value="€38.4M" delta="+€6.2M quarter" accent="gold"/><StatTile icon={Users} label="Investor Network" value="126" delta="18 new partners" accent="cyan"/><StatTile icon={Building} label="Academies Funded" value="14" delta="Across 9 markets" accent="lime"/><StatTile icon={TrendingUp} label="Projected Return" value="21.4%" delta="Blended portfolio" accent="rose"/></div>
    <GamePanel className="relative mt-5 overflow-hidden p-6 pitch-grid"><div className="absolute right-[-5%] top-[-70%] size-[450px] rounded-full border border-amber-300/10"/><div className="relative grid gap-7 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><p className="text-[8px] font-black uppercase tracking-[.2em] text-amber-300">Football Capital Intelligence</p><h2 className="font-display mt-2 max-w-2xl text-3xl uppercase italic">Invest in infrastructure.<br/><span className="text-[#a3ff12]">Unlock human potential.</span></h2><p className="mt-3 max-w-xl text-[9px] leading-5 text-slate-500">A compliant deal room connecting qualified partners with academies, performance projects and structured player-development opportunities.</p><div className="mt-5 flex gap-2"><Button>Explore Opportunities</Button><Button variant="secondary">Investment Thesis</Button></div></div><div className="grid grid-cols-2 gap-3"><div className="rounded-xl border border-white/[.08] bg-black/20 p-4"><ShieldCheck size={16} className="text-[#a3ff12]"/><p className="mt-4 text-[8px] text-slate-600">DUE DILIGENCE</p><p className="mt-1 text-xs font-black">100% VERIFIED</p></div><div className="rounded-xl border border-white/[.08] bg-black/20 p-4"><Globe2 size={16} className="text-cyan-300"/><p className="mt-4 text-[8px] text-slate-600">ACTIVE MARKETS</p><p className="mt-1 text-xs font-black">18 COUNTRIES</p></div><div className="col-span-2 rounded-xl border border-white/[.08] bg-black/20 p-4"><div className="flex justify-between text-[8px] font-bold text-slate-500"><span>PORTFOLIO DEPLOYMENT</span><span>€38.4M / €60M</span></div><div className="mt-3"><Meter value={64} color="gold"/></div></div></div></div></GamePanel>
    <section className="mt-6"><SectionHeader kicker="Curated Deal Rooms" title="Live Opportunities" action={<button className="text-[8px] font-black uppercase text-cyan-300">View full marketplace →</button>}/><div className="grid gap-4 lg:grid-cols-3">{opportunities.map(o=><GamePanel key={o.title} className="glass-hover overflow-hidden"><div className="relative h-40"><Image src={o.image} fill sizes="500px" alt={o.title} className="object-cover opacity-55"/><div className="absolute inset-0 bg-gradient-to-t from-[#08131e] to-transparent"/><span className="absolute left-4 top-4 rounded-md border border-amber-300/20 bg-black/50 px-2 py-1 text-[7px] font-black tracking-wider text-amber-300">{o.type}</span></div><div className="p-5"><h3 className="text-[12px] font-black uppercase italic">{o.title}</h3><p className="mt-1 text-[8px] text-slate-600">{o.region}</p><div className="mt-5 grid grid-cols-3 text-center"><div><p className="text-[7px] text-slate-600">TARGET</p><p className="mt-1 text-xs font-black">{o.target}</p></div><div className="border-x border-white/[.07]"><p className="text-[7px] text-slate-600">RETURN</p><p className="mt-1 text-xs font-black text-[#a3ff12]">{o.return}</p></div><div><p className="text-[7px] text-slate-600">RISK</p><p className="mt-1 text-xs font-black text-amber-300">{o.risk}</p></div></div><div className="mt-5 flex justify-between text-[8px] text-slate-500"><span>FUNDED</span><span>{o.raised}%</span></div><div className="mt-2"><Meter value={o.raised} color="gold"/></div><Button variant="secondary" className="mt-4 w-full">Enter Deal Room <ArrowUpRight size={12}/></Button></div></GamePanel>)}</div></section>
  </div>;
}
