import { ArrowUp, Crown, Flame, Globe2, Shield, Trophy, Users, Zap } from "lucide-react";
import { GamePanel, LivePill, Meter, SectionHeader, StatTile } from "@/components/game-ui";

const agents = [
  {rank:1,name:"Sofia Moretti",agency:"Vantage Global",country:"ITA",rep:978,value:"€684M",deals:31,badge:"ICON"},
  {rank:2,name:"Daniel Okafor",agency:"Apex Sports",country:"NGA",rep:954,value:"€592M",deals:28,badge:"ICON"},
  {rank:3,name:"Mateo Ruiz",agency:"RMG Partners",country:"ESP",rep:938,value:"€548M",deals:26,badge:"ELITE"},
  {rank:184,name:"Alex Oliveira",agency:"Eleven",country:"MLT",rep:842,value:"€147M",deals:18,badge:"ELITE"},
  {rank:185,name:"Leon Weber",agency:"Neue Klasse",country:"GER",rep:840,value:"€163M",deals:17,badge:"ELITE"},
];

export default function Competition() {
  return <div className="mx-auto max-w-[1500px] animate-in"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="mb-2 flex items-center gap-3"><LivePill>Season rankings live</LivePill><span className="text-[8px] font-bold uppercase tracking-wider text-slate-700">12,846 verified agents</span></div><h1 className="font-display text-3xl uppercase italic sm:text-[42px]">Agent League</h1><p className="mt-1.5 text-xs text-slate-500">Reputation is earned in every room, every deal and every career.</p></div><div className="rounded-xl border border-amber-300/15 bg-amber-300/[.05] px-4 py-3 text-right"><p className="text-[7px] font-black uppercase tracking-wider text-amber-300">Your world rank</p><p className="font-display mt-1 text-2xl">#184 <span className="text-[9px] text-[#a3ff12]">↑23</span></p></div></div>
    <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatTile icon={Trophy} label="Reputation" value="842" delta="+18 this week" accent="gold"/><StatTile icon={Flame} label="Deal Streak" value="07" delta="Personal best" accent="rose"/><StatTile icon={Users} label="Client Value" value="€147M" delta="Top 8%" accent="cyan"/><StatTile icon={Globe2} label="Global Reach" value="14" delta="Active markets" accent="lime"/></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><GamePanel className="overflow-hidden"><div className="flex items-center justify-between border-b border-white/[.07] p-5"><div><p className="text-[8px] font-black uppercase tracking-[.2em] text-amber-300">Global standings</p><h2 className="mt-1 text-sm font-black uppercase italic">Top Transfer Agents</h2></div><Trophy size={17} className="text-amber-300"/></div><div className="divide-y divide-white/[.06]">{agents.map(a=><div key={a.name} className={`grid items-center gap-3 p-4 sm:grid-cols-[60px_1fr_90px_90px_75px] ${a.name==="Alex Oliveira"?"bg-cyan-300/[.055]":""}`}><div className="flex items-center gap-2"><span className={`font-display text-xl ${a.rank<=3?"text-amber-300":"text-slate-500"}`}>#{a.rank}</span>{a.name==="Alex Oliveira"&&<ArrowUp size={11} className="text-[#a3ff12]"/>}</div><div><p className="text-[10px] font-black uppercase italic">{a.name}</p><p className="mt-1 text-[7px] font-bold text-slate-600">{a.agency} · {a.country}</p></div><div><p className="text-[7px] text-slate-600">REPUTATION</p><p className="mt-1 text-xs font-black">{a.rep}</p></div><div><p className="text-[7px] text-slate-600">CLIENT VALUE</p><p className="mt-1 text-xs font-black">{a.value}</p></div><span className={`justify-self-start rounded-md border px-2 py-1 text-[7px] font-black ${a.badge==="ICON"?"border-amber-300/25 text-amber-300":"border-cyan-300/20 text-cyan-300"}`}>{a.badge}</span></div>)}</div></GamePanel>
      <div className="space-y-5"><GamePanel className="p-5"><SectionHeader kicker="Division Status" title="Elite III" action={<Crown size={17} className="text-amber-300"/>}/><div className="mt-5 text-center"><div className="mx-auto grid size-24 place-items-center rounded-full border border-amber-300/25 bg-amber-300/[.06] shadow-[0_0_35px_rgba(247,198,93,.1)]"><Shield size={38} className="text-amber-300"/></div><p className="mt-4 text-[9px] font-bold text-slate-500">158 reputation to Icon division</p><div className="mt-3"><Meter value={84} color="gold"/></div></div></GamePanel><GamePanel className="p-5"><SectionHeader kicker="Weekly Duel" title="Deal Maker Cup" action={<Zap size={15} className="text-[#a3ff12]"/>}/><p className="text-[9px] leading-5 text-slate-500">Close the highest combined transfer value before Sunday.</p><div className="mt-4 flex items-end justify-between"><div><p className="text-[7px] text-slate-600">YOUR TOTAL</p><p className="mt-1 text-lg font-black">€68.5M</p></div><div className="text-right"><p className="text-[7px] text-slate-600">LEADER</p><p className="mt-1 text-lg font-black text-amber-300">€92.0M</p></div></div><div className="mt-3"><Meter value={74} color="lime"/></div></GamePanel></div></div>
  </div>;
}
